#define MAX_DISKNAME_LENGTH 256

#define BLOCK_SIZE 1024
#define TOTAL_BLOCKS 1048576
#define BITMAP_BYTES BLOCK_SIZE * 128
// BLOCK_SIZE * 128 bitmap blocks
#define DISK_BLOCKS TOTAL_BLOCKS - 128 - 1
// 1048576 total blocks - 1 index block - 128 bitmap blocks

#define DATA_BYTES_LIMIT BLOCK_SIZE * 252
// BLOCK_SIZE * 252 data blocks
#define SIMPLE_DIRECT_BYTES_LIMIT BLOCK_SIZE * 256 + DATA_BYTES_LIMIT
// BLOCK_SIZE * 256 data blocks + DATA_BYTES_LIMIT
#define DOUBLE_DIRECT_BYTES_LIMIT BLOCK_SIZE * 256 * 256 + SIMPLE_DIRECT_BYTES_LIMIT
// BLOCK_SIZE * 256 simple blocks * 256 data blocks + SIMPLE_DIRECT_BYTES_LIMIT
#define TRIPLE_DIRECT_BYTES_LIMIT BLOCK_SIZE * 256 * 256 * 256 + DOUBLE_DIRECT_BYTES_LIMIT
// BLOCK_SIZE * 256 double blocks * 256 simple blocks * 256 data blocks + DOUBLE_DIRECT_BYTES_LIMIT
